ZenUml/confluence-plugin-cloud

atlassian-connect.json, src/utils/BaseMacro.js, tests/unit/Macro.spec.js
Fix the content property error when saving macro.
=> Remove the save of content property

package.json, src/GTagConfig.ts, src/main.ts, src/sequence-editor-dialog.ts, src/sequence-editor.ts, src/sequence-viewer-dialog.ts, src/sequence-viewer.ts, yarn.lock
=> Added gtag for vue-sequence components.

package.json, yarn.lock
Note that this is wrangler 2.x. Wrangler 1.x is at @cloudflare/wrangler.
=> Updated wrangler.

src/components/DocumentList/DocumentList.vue, src/model/ApWrapper2.ts, src/model/ContentProvider/CustomContentStorageProvider.ts, src/model/Diagram/Diagram.ts, src/model/IApWrapper.ts, src/model/ICustomContent.ts, src/utils/timer.ts
- load more custom content beyond the default page limit, up to 1000
- group items by containing page, sort by page title
- track search custom content events
=> Improve embed macro editor

package.json, yarn.lock
=> Updated dependency @zenuml/core.

src/model/Attachment.js
This is a quick fix by ensuring only one process of creating attachment is running. In future, we can investigate more on the multiple "diagramLoaded" events.
=> Fix create attachment error after sequence diagram edit through page edit

src/model/Ap/MockedResponse/custom-content-by-id-v1-diagram-sequence.json, src/model/MockAp.ts, src/model/MockApConfluence.ts
This is used for local testing.
=> Return full mocked JSON for sequence diagram viewer.

tests/e2e/demoPage.js
Use keyboard typing to simulate username / password input.
=> Fix e2e login

src/components/Header/Header.vue, tests/e2e/demoPage.js
=> 482 easily select and insert recent or template diagrams

src/graph-main-viewer.ts, src/model/ApWrapper2.ts, src/sequence-viewer.ts, src/swagger-ui.ts
Events percentage:
- get_attachments: 54%
- before_create_attachment: 23%
=> Remove get_attachments/before_create_attachment analytic events

package.json, src/components/DiagramPortal.vue, src/components/Mermaid.vue, src/components/Viewer/GenericViewer.vue, yarn.lock
Bump mermaid js to v10 to fix rendering issue.
Use async/await syntax since [mermaid js scraps the callback api](https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md#mermaidrender-is-async-and-doesnt-accept-callbacks)
=> fix: :arrow_up: bump mermaid to v10 and use async/await 

functions/atlassian-connect.json, public/dashboard.html, src/components/DocumentList/DashboardDocumentList.vue, src/components/DocumentList/DocumentList.vue, src/dashboard.ts, src/model/ApWrapper2.ts, src/model/Attachment.js, src/model/ContentProvider/CustomContentStorageProvider.ts, src/model/page/AtlasDocFormat.ts, src/model/page/ConfluencePage.ts, vue.config.js
First version dashboard page based on embed-editor page
=> Add side bar link and dashboard page

functions/atlassian-connect.json, src/components/DocumentList/DashboardDocumentList.vue
This MR enables users to edit macros on dashboard.
=> Add editing feature in Dashboard

public/dashboard.html, public/js/demo/demoPage.js, src/components/DocumentList/DashboardDocumentList.vue
Dashboard right side panel when there's no content:
=> Add "Get Started" button in dashboard when no content to create demo page

src/components/CSAT/index.vue
https://github.com/ZenUml/confluence-plugin-cloud/assets/125171539/0431f1fd-f903-4d67-888d-15efcb972e83
=> feat: implemented new style for CSAT #578

src/components/DocumentList/DashboardDocumentList.vue
https://github.com/ZenUml/confluence-plugin-cloud/assets/48118719/7dfa7128-2f8f-47e3-a83e-3ca4ae4cc59f
=> fix: auto load next page if has more data but no scroll

src/components/DocumentList/DashboardDocumentList.vue, src/model/ApWrapper2.ts, src/model/page/AtlasPage.ts
This change only impacts the embed editor, not the dashboard page.
=> Fallback to "get custom content by type" api when "search all custom content" returns empty

functions/attachment.ts, functions/descriptor.js, functions/utils/white-list.ts
pdf export sample:
[4 final.pdf](https://github.com/ZenUml/confluence-plugin-cloud/files/13809798/4.final.pdf)
=> feat: include upgrading instructions in exported PDF for Lite version

src/components/DocumentList/DashboardDocumentList.vue
Tested using two subdomains with and without data respectively, it works.
=> fix: displayed 'Get stared' when back to list view

.gitignore, drawio/editor.html, src/components/DrawIoExtension/DrawIoExtension.vue, src/components/DrawIoExtension/components/CreateGraph.vue, src/components/DrawIoExtension/components/DrawIoHeader.vue, src/graph-main-editor.ts
=> feat: graph header for display and rename titles

src/components/DocumentList/DashboardDocumentList.vue, src/utils/window.ts
=> feat: add track event  'dashboard-full-screen'

src/dashboard.ts
https://github.com/ZenUml/confluence-plugin-cloud/issues/638
=> fix: should initializeContext before track load_dashboard event

src/components/Sequence.vue
=> fix: theme modal incorrect zIndex
